### ISSUE TITLE
"panic: Watch already in progress" on rollback

### ISSUE THREAD

**Issue by zikaeroh** [jackc/pgconn#29] opened 2020-02-27 18:42 UTC
I got this while I was debugging, where I forgot my context had a timeout and it was canceled as I was stepping leading to a rollback (since I rollback on an error instead of committing). It seems like there's a ContextWatcher race on rollback.

```
panic: Watch already in progress

goroutine 22113 [running]:
github.com/jackc/pgconn/internal/ctxwatch.(*ContextWatcher).Watch(0xc000096740, 0x145f440, 0xc0001d0840)
	/home/jake/go/pkg/mod/github.com/jackc/pgconn@v1.3.2/internal/ctxwatch/context_watcher.go:33 +0xdc
github.com/jackc/pgconn.(*PgConn).Close(0xc000d1e2c0, 0x145f440, 0xc0001d0840, 0x0, 0x0)
	/home/jake/go/pkg/mod/github.com/jackc/pgconn@v1.3.2/pgconn.go:497 +0x136
github.com/jackc/pgx/v4.(*Conn).die(0xc000955560, 0x1447020, 0xc0001d0800)
	/home/jake/go/pkg/mod/github.com/jackc/pgx/v4@v4.4.1/conn.go:357 +0x103
github.com/jackc/pgx/v4.(*dbTx).Rollback(0xc0008897d0, 0x145f480, 0xc0001a2010, 0x0, 0x0)
	/home/jake/go/pkg/mod/github.com/jackc/pgx/v4@v4.4.1/tx.go:186 +0x24f
github.com/jackc/pgx/v4/stdlib.wrapTx.Rollback(0x1467e00, 0xc0008897d0, 0x0, 0x0)
	/home/jake/go/pkg/mod/github.com/jackc/pgx/v4@v4.4.1/stdlib/sql.go:542 +0x5d
database/sql.(*Tx).rollback.func1()
	/usr/lib/go/src/database/sql/sql.go:2112 +0x4a
database/sql.withLock(0x144f6e0, 0xc000509e00, 0xc00074b778)
	/usr/lib/go/src/database/sql/sql.go:3184 +0x77
database/sql.(*Tx).rollback(0xc000ab4c80, 0x1, 0x0, 0x0)
	/usr/lib/go/src/database/sql/sql.go:2111 +0xce
database/sql.(*Tx).awaitDone(0xc000ab4c80)
	/usr/lib/go/src/database/sql/sql.go:2008 +0x67
created by database/sql.(*DB).beginDC
	/usr/lib/go/src/database/sql/sql.go:1723 +0x34e
Process exiting with code: 0
```

**Comment by jackc** [comment] 2020-02-29 15:52
pgconn itself doesn't have a concept of transactions. It is simply executing `begin` or `rollback` statements that are issued from pgx.

According to the stack trace executing the rollback failed - which is expected if the context is already canceled. Because a rollback failure leaves the connection in an unknown state pgx closes connections that have a rollback failure. It is closing the connection that failed.

I've tried to duplicate this but have been unable to. Do you have a way of reproducing this?

**Comment by zikaeroh** [comment] 2020-02-29 21:01
I don't have an effective way, but I'll try to go back and do exactly what I was doing before to try and see if that's consistent enough.

**Comment by zikaeroh** [comment] 2020-04-06 01:08
Sorry it's been so long, but I do have a reliable repro I discovered today. It appears to happen only when a `sql.Rows` has been partially read, at least after one `rows.Next()` with no `Scan()`.

Unfortunately my setup is convoluted (a local replacement of the ORM-alike I use and am currently optimizing), where I inserted a `panic` in some column to struct binding code that's called just after `rows.Next()`.

My assumption is that the procedure is:

1. BeginTx to start a transaction.
1. Defer a function to call `Rollback` if a panic occurs (with a boolean that is only false if no panic happens). See: https://github.com/hortbot/hortbot/blob/f3b349c5cdb5b87a923d6c6e1b974308cf974f8f/internal/pkg/dbx/dbx.go#L33
1. Do a `QueryContext` and get back `*sql.Rows`.
1. Call `rows.Next()`.
1. Panic.
1. Call `tx.Rollback` in the deferred function.
1. Get the "Watch already in progress" panic via pgx's Rollback -> die -> pgconn Close.

This trace in my real code looks like:


```
            github.com/hortbot/hortbot/internal/pkg/ctxlog.Error
            	/home/jake/zikaeroh/hortbot/hortbot/internal/pkg/ctxlog/ctxlog.go:56
            github.com/hortbot/hortbot/internal/bot.(*Bot).handle.func1
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:95
            runtime.gopanic
            	/usr/lib/go/src/runtime/panic.go:967
            github.com/jackc/pgconn/internal/ctxwatch.(*ContextWatcher).Watch
            	/home/jake/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/internal/ctxwatch/context_watcher.go:33
            github.com/jackc/pgconn.(*PgConn).Close
            	/home/jake/go/pkg/mod/github.com/jackc/pgconn@v1.5.0/pgconn.go:497
            github.com/jackc/pgx/v4.(*Conn).die
            	/home/jake/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/conn.go:357
            github.com/jackc/pgx/v4.(*dbTx).Rollback
            	/home/jake/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/tx.go:186
            github.com/jackc/pgx/v4/stdlib.wrapTx.Rollback
            	/home/jake/go/pkg/mod/github.com/jackc/pgx/v4@v4.6.0/stdlib/sql.go:546
            database/sql.(*Tx).rollback.func1
            	/usr/lib/go/src/database/sql/sql.go:2112
            database/sql.withLock
            	/usr/lib/go/src/database/sql/sql.go:3184
            database/sql.(*Tx).rollback
            	/usr/lib/go/src/database/sql/sql.go:2111
            database/sql.(*Tx).Rollback
            	/usr/lib/go/src/database/sql/sql.go:2126
            github.com/hortbot/hortbot/internal/pkg/dbx.Transact.func1
            	/home/jake/zikaeroh/hortbot/hortbot/internal/pkg/dbx/dbx.go:50
            runtime.gopanic
            	/usr/lib/go/src/runtime/panic.go:967
            github.com/volatiletech/sqlboiler/queries.ptrsFromMapping2
            	/home/jake/zikaeroh/sqlboiler/queries/reflect.go:362
            github.com/volatiletech/sqlboiler/queries.bind
            	/home/jake/zikaeroh/sqlboiler/queries/reflect.go:288
            github.com/volatiletech/sqlboiler/queries.(*Query).Bind
            	/home/jake/zikaeroh/sqlboiler/queries/reflect.go:150
            github.com/hortbot/hortbot/internal/bot.cmdQuoteSearch
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/cmd_quote.go:260
            github.com/hortbot/hortbot/internal/bot.handlerMap.run
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handlers.go:70
            github.com/hortbot/hortbot/internal/bot.handlerMap.Run
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handlers.go:38
            github.com/hortbot/hortbot/internal/bot.cmdQuote
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/cmd_quote.go:36
            github.com/hortbot/hortbot/internal/bot.handlerMap.run
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handlers.go:70
            github.com/hortbot/hortbot/internal/bot.handlerMap.RunWithCooldown
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handlers.go:42
            github.com/hortbot/hortbot/internal/bot.tryBuiltinCommand
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:520
            github.com/hortbot/hortbot/internal/bot.tryCommand
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:497
            github.com/hortbot/hortbot/internal/bot.handleSession
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:398
            github.com/hortbot/hortbot/internal/bot.(*Bot).handlePrivMsg.func1
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:147
            github.com/hortbot/hortbot/internal/pkg/dbx.Transact.func2
            	/home/jake/zikaeroh/hortbot/hortbot/internal/pkg/dbx/dbx.go:58
            github.com/hortbot/hortbot/internal/pkg/dbx.Transact
            	/home/jake/zikaeroh/hortbot/hortbot/internal/pkg/dbx/dbx.go:63
            github.com/hortbot/hortbot/internal/bot.(*Bot).handlePrivMsg
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:141
            github.com/hortbot/hortbot/internal/bot.(*Bot).handle
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:102
            github.com/hortbot/hortbot/internal/bot.(*Bot).Handle
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/handle.go:69
            github.com/hortbot/hortbot/internal/bot/btest.(*scriptTester).handleM.func1
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/btest/irc.go:57
            github.com/hortbot/hortbot/internal/bot/btest.(*scriptTester).test
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/btest/script_tester.go:207
            github.com/hortbot/hortbot/internal/bot/btest.RunScript
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/btest/script_tester.go:49
            github.com/hortbot/hortbot/internal/bot_test.TestScripts.func1
            	/home/jake/zikaeroh/hortbot/hortbot/internal/bot/script_test.go:27
            testing.tRunner
            	/usr/lib/go/src/testing/testing.go:992
```

Hopefully this is enough to go off of, but if not I can attempt to make something more condensed...

**Comment by zikaeroh** [comment] 2020-04-06 04:12
I've managed to make this self contained. There's one extra missing piece; the database connection needs to be shared by multiple goroutines.

Here is the reproducer; it requires that you have a docker instance on the local machine to spin up a temporary database.

https://gist.github.com/zikaeroh/39b42c6ab2ee951099a2f80c56406e06

**Comment by zikaeroh** [comment] 2020-04-06 04:28
I've condensed the gist even more; it's just `BeginTx`, `QueryContext`, and `Rollback` in 4 separate goroutines.

**Closed** 2020-04-08 00:39 UTC

**Comment by jackc** [comment] 2020-04-08 00:41
Thanks, I was able to diagnose the problem. The root bug was calling `Close()` with a cancelable context while a cancelable query was already in progress.

This should be resolved now.

**Comment by zikaeroh** [comment] 2020-04-08 01:05
Thanks for the update. Unfortunately, I'm not sure that this is entirely fixed, or it has at least exposed a new error. I'm seeing "i/o timeout" from the `QueryExecute` calls, or timeouts on `BeginTx`.

Here is the output of the gist (which I've updated to use your new commit).

```
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55242->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55236->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55214->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55212->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55220->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55176->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55238->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55232->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55224->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55222->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55218->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55206->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55198->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55202->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55184->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55208->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55170->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55190->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55210->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55182->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55172->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55192->[::1]:32786: i/o timeout
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:54: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:32786: operation was canceled)
2020/04/07 18:03:30 main.go:60: read tcp [::1]:55216->[::1]:32786: i/o timeout
```

I don't think there's anything wrong with the gist (besides a missing `rows.Close()`, which does not appear to matter); it's simulating multiple separate goroutines sharing a connection and opening their own transactions and doing a read-only query and not consuming all of the results.

Maybe this is a new error that was hidden by the watcher panic, but I don't think this is good either.

But, at least these are errors that can be handled, rather than fully fledged panics. :slightly_smiling_face:

**Comment by zikaeroh** [comment] 2020-04-08 01:11
Ah, the timeouts were because I returned the rollback error thinking it would always succeed. In fact, with another update to the gist, I get a bunch of:

```
2020/04/07 18:10:29 main.go:71: conn busy
2020/04/07 18:10:29 main.go:71: conn busy
2020/04/07 18:10:29 main.go:71: conn busy
2020/04/07 18:10:29 main.go:71: conn busy
2020/04/07 18:10:29 main.go:71: conn busy
```

Now, if I instead use `github.com/lib/pq`, I get a bunch of:

```
2020/04/07 18:10:56 main.go:71: unexpected command tag SELECT
2020/04/07 18:10:56 main.go:71: unexpected command tag SELECT
2020/04/07 18:10:56 main.go:71: unexpected command tag SELECT
2020/04/07 18:10:56 main.go:71: unexpected command tag SELECT
```

I'm not sure what to make of this; I think that this is a valid set of things to do with a database and transactions.

**Comment by zikaeroh** [comment] 2020-04-08 01:16
If you'd like, I can open this as a new issue. Whatever works best for your tracking.

**Comment by jackc** [comment] 2020-04-08 13:51
There is an error in the example.

```go
			rows, err := tx.QueryContext(ctx, "SELECT table_name FROM information_schema.tables")
			if err != nil {
				log.Println(err)
				return err
			}

			if !rows.Next() {
				panic("no rows")
			}
			defer rows.Close()

			if err := tx.Rollback(); err != nil {
				log.Println(err)
			}
```

Because `rows.Close()` is deferred, `tx.Rollback()` happens first. In `pgx` you get the `conn busy` error because `pgx` ensures that the connection is in a valid state before sending another query (`rollback`). For `lib/pq` it appears the error is it _does_ send the `rollback` command -- but since it hadn't finished reading the results of the previous select statement it gets the selects command tag of `SELECT` instead of the `ROLLBACK` it expected.

**Comment by zikaeroh** [comment] 2020-04-08 16:29
You're totally right. Ensuring the calls happen in the right order (which happens in my actual code, not this example) fixes things.

Thanks for bearing with me!
